# См. https://pre-commit.comдля получения дополнительной информации.
# См. https://pre-commit.com/hooks.htmlдля получения дополнительных хуков.
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace

-   repo: local
    hooks:
    # Запустите astyle для подготовленных файлов с расширениями c и h, найденных в каталогах.
    # указан в шаблоне регулярного выражения файлов. Игнорирование файлов в шаблоне исключения.
    -   id: format-source
        name: Formatting source files
        entry: astyle --options=scripts/code-format.cfg --ignore-exclude-errors
        stages: [ commit ]
        language: system
        pass_filenames: true
        verbose: true
        files: |
          (?x)^(
              demos/ |
              examples/ |
              src/ |
              tests/
          )
        exclude: |
          (?x)^(
              demos/high_res/fonts/ |
              src/libs/ |
              src/lv_conf_internal.h |
              tests/test_images
           )
        types_or: ["c", "header"]
    # Если кажется, что файл соответствуетlv_templ.c/lv_templ.h, убедитесь, что часть
    # которые зависят от имени файла, верны.
    -   id: template-check
        name: Comparing file templates with file names
        entry: python scripts/lv_templ_check.py --fix --quiet
        stages: [ commit ]
        language: system
        pass_filenames: false
        verbose: true
        types_or: ["c", "header"]
-   repo: https://github.com/crate-ci/typos
    rev: v1.16.20
    hooks:
    -   id: typos
        exclude: |
            (?x)^(
                src/libs/
             )
