// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: Thermostat

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Label_Slider1;
extern void ui_event_Fan_Speed_Control1(lv_event_t * e);
extern lv_obj_t * ui_Fan_Speed_Control1;
extern void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

