// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: Thermostat

#include "ui.h"
#include "esp_log.h"

void fan_speed_value(lv_event_t * e)
{
	lv_obj_t * slider = lv_event_get_target(e);
	int32_t value = lv_slider_get_value(slider);
	ESP_LOGI("UI", "Значение скорости: %" PRId32, value);
}
